# Report on SSD-Analysis

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE)
```


## Aggregated data:

```{r agg_data}
kable(df, digits = 4)
```

```{r plot_agg_data}
df <- df[order(df[[input$y]]), ]
df$frac <- ppoints(df[[input$y]], 0.5)
nobs <- nrow(df)
df_sort <- df[order(df[[input$y]]), ]
half <- ceiling(nobs / 2)
if (!input$log_x)
  half <- nobs - 1
lab_right <- df_sort[1:half, ]
lab_left <- df_sort[(half + 1):nobs, ]

p <- ggplot() +
  theme_bw() +
  labs(x  = 'Concentration', y = 'Potentially Affected Fraction')  +
  theme(legend.position = 'bottom')

if (input$group != '__none__')
  p <- p + aes_string(col = input$group)

p <- p + 
  geom_point(data = df, aes_string(x = input$y, y = 'frac')) +
  # lowest 35 to the right
  geom_text(data = lab_right, 
            aes_string(x = max(df[[input$y]]), 
                       y = 'frac', 
                       label = input$species), 
            hjust = 1, 
            show.legend = FALSE) +
  # highest 35 to the left
  geom_text(data = lab_left, 
            aes_string(x = min(df[[input$y]]), 
                       y = 'frac', 
                       label = input$species), 
            hjust = 0, 
            show.legend = FALSE) 

if (input$log_x) {
  p <- p + scale_x_log10()
}
p
```



## Model:

* Model fitted: `r input$model`
* Bootstrap method: `r input$boot_method`
* No. boot samples: `r input$nboot`

```{r model_table}
est <- t(hcxs$quantiles)
cis <- t(cis$quantCI)
out <- data.frame(HC = hcx,
                   Estimate = est,
                   Lower = cis[ , 1],
                   Upper = cis[ , 2])
rownames(out) <- NULL
# out <- round_df(out, digits = 4)
kable(out, digits = 4)
```


```{r model_plot}
df <- df[order(df[[input$y]]), ]
df$frac <- ppoints(df[[input$y]], 0.5)
nobs <- nrow(df)
df_sort <- df[order(df[[input$y]]), ]
half <- ceiling(nobs / 2)
if (!input$log_x)
  half <- nobs - 1
lab_right <- df_sort[1:half, ]
lab_left <- df_sort[(half + 1):nobs, ]

p <- ggplot() +
  theme_bw() +
  labs(x  = 'Concentration', y = 'Potentially Affected Fraction')  +
  theme(legend.position = 'bottom')

if (input$log_x)
  p <- p + scale_x_log10()

if (input$plot_samps)
  p <- p + geom_line(data = bootdat,
                     aes(x = newxs, y = value, group = variable),
                     col = 'steelblue', 
                     alpha = 10 / input$nboot)

if (input$group != '__none__') {
  p <- p + 
    geom_point(data = df,
               aes_string(x = input$y, 
                          y = 'frac', 
                          col = input$group)) +
    # lowest 35 to the right
    geom_text(data = lab_right, 
              aes_string(x = max(df[[input$y]]), 
                         y = 'frac', 
                         label = input$species), 
              hjust = 1, 
              show.legend = FALSE) +
    # highest 35 to the left
    geom_text(data = lab_left, 
              aes_string(x = min(df[[input$y]]), 
                         y = 'frac', 
                         label = input$species), 
              hjust = 0, 
              show.legend = FALSE) 
} else {
  p <- p + 
    geom_point(data = df,
               aes_string(x = input$y, y = 'frac')) +
    # lowest 35 to the right
    geom_text(data = df_sort[1:half, ], 
              aes_string(x = max(df[[input$y]]), 
                         y = 'frac', 
                         label = input$species), 
              hjust = 1, 
              size = 4, 
              show.legend = FALSE) +
    # highest 35 to the left
    geom_text(data = df_sort[(half + 1):nobs, ], 
              aes_string(x = min(df[[input$y]]), 
                         y = 'frac', 
                         label = input$species), 
              hjust = 0, 
              size = 4, 
              show.legend = FALSE) 
}

p <- p + 
  geom_line(data = pdat, aes(x = newxs, y = py), col = 'red') +
  geom_line(data = pdat, aes(x = newxs, y = lwr), linetype = 'dashed') +
  geom_line(data = pdat, aes(x = newxs, y = upr), linetype = 'dashed') 
p
```



## Appendix
### Raw data:

```{r}
kable(df_raw)
```
